branches:
  only:
    - gh-pages

language: node_js
node_js:
  - 0.8

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --quiet -g karma
  - ./scripts/web-server.js > /dev/null &
  - sleep 1 # give server time to start

script:
  - karma start config/testacular-e2e.conf.js --reporters=dots --browsers=Firefox

env:
  global:
    - secure: "VX14P2aBAYhNcxowOORAJQpys6S+dr0wpg+VV67KDDmBs4LKm6om9q28O6Ph\nzvFVFzwHxUIgOlaKElDu8I85I98U1G+ogI+Miga56ykNAM9R5YXGzAebqMDx\nblkBlQPejnPLpES9/gB0gMjNFUKcrslMoREi73GEtfVR51VHC/A="

after_success:
- cd ..
- ls
- wget http://googleappengine.googlecode.com/files/google_appengine_1.7.4.zip -nv
- unzip -q google_appengine_1.7.4.zip
- google_appengine/appcfg.py --oauth2_refresh_token=$GAE_TOKEN update awesome-start